""" adding new column to db usrs

Revision ID: 5f715a97a9cb
Revises: 7b3cd0ee528d
Create Date: 2024-09-28 15:36:09.789082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5f715a97a9cb'
down_revision = '7b3cd0ee528d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrolesenum = postgresql.ENUM('super_admin', 'admin', 'user', name='userrolesenum')
    userrolesenum.create(op.get_bind())

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('super_admin', 'admin', 'user', name='userrolesenum')
                                      , nullable=False, server_default='user' ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
